apiVersion: v1
kind: Service
metadata:
  name: currencyconverter-aws
  namespace: default
  labels:
    app: currencyconverter-aws
spec:
  selector:
    app: currencyconverter-aws
    type: ClusterIP
  ports:
    - name: http
      port: 8080